---
- hosts: ti.riv
  roles:
    - yii
    - { role: mysql, sudo: yes, tags: mysql }
    - { role: nginx, sudo: yes, tags: nginx }

- hosts: ti.pyro
  roles:
    - yii
    - { role: mysql, sudo: yes, tags: mysql }
    - { role: nginx, sudo: yes, tags: nginx }
